services:
  # --- BANCO DE DADOS ---
  db:
    image: postgres:16-alpine 
    container_name: hackathon-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hackathondb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hackathondb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - hackathon-net

  # --- BACKEND ---
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: hackathon-backend
    ports:
      - "8080:8080"
    environment:
      # Sobrescreve a URL do properties para garantir conex√£o interna
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hackathondb
    depends_on:
      db:
        condition: service_healthy
    networks:
      - hackathon-net

  # --- FRONTEND ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hackathon-frontend
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/scorebank
      - /app/node_modules

    command: ["ng", "serve", "--host", "0.0.0.0"]
    depends_on:
      - backend
    networks:
      - hackathon-net

networks:
  hackathon-net:
    driver: bridge
