on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:

      - name: Check
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Install Make
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: Destroy ec2 already running the project
        id: destroy
        run: make tf-destroy
        working-directory: terraform

      - name: Deploys on AWS
        id: apply
        run: make tf-apply
        working-directory: terraform
        
      - name: Publish Terraform Output & Expose URL
        id: get_url
        run: |
          APP_URL=$(terraform output -raw app_url)
          
          # Publica no Job Summary
          echo "## üîó Link da Aplica√ß√£o Deployada" >> $GITHUB_STEP_SUMMARY
          echo "**A sua aplica√ß√£o est√° pronta!** Clique no link abaixo para acess√°-la:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "[**Acessar Aplica√ß√£o**]($APP_URL)" >> $GITHUB_STEP_SUMMARY
          
          # EXPOE a URL para ser usada em passos seguintes
          echo "app_url=$APP_URL" >> $GITHUB_OUTPUT
          
        working-directory: terraform

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: deploy-${{ github.sha }}
          name: Deploy Autom√°tico | Commit ${{ github.sha }}
          body: |
            ## üéâ Novo Lan√ßamento: Aplica√ß√£o Implantada!
            
            O deploy da aplica√ß√£o foi conclu√≠do com sucesso.
            
            Acesse a nova vers√£o diretamente por este link:
            
            [**Acessar Aplica√ß√£o**](${{ steps.get_url.outputs.app_url }})