on:
  push:
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Check
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Install Make
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: Destroy ec2 already running the project
        id: destroy
        run: make tf-destroy
        working-directory: terraform

      - name: Deploys on AWS
        id: apply
        run: make tf-apply
        working-directory: terraform
      
      - name: Publish Terraform Output
        run: |
          APP_URL=$(terraform output -raw app_url)
                    
          echo "## ðŸ”— Link da AplicaÃ§Ã£o Deployada" >> $GITHUB_STEP_SUMMARY
          echo "**A sua aplicaÃ§Ã£o estÃ¡ pronta!** Clique no link abaixo para acessÃ¡-la:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "[**Acessar AplicaÃ§Ã£o**]($APP_URL)" >> $GITHUB_STEP_SUMMARY
          
        working-directory: terraform